# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubyconf.ph" # the base hostname & protocol for your site
meet_the_team:
  rubyists:
    - name: 'Christopher Rigor'
      twitter: crigor
      github: crigor
      image: christopher.jpg
    - name: 'Ramon Tayag'
      twitter: rtayag
      github: ramontayag
      image: ramon.jpeg
    - name: 'Eumir Gaspar'
      twitter: benjobatumbakal
      github: corroded
      image: eums.jpg
    - name: 'Chris Menina'
      github: kristm
      image: krist.png
  staff:
    - name: 'Sam Rigor'
      image: sam.jpg
    - name: 'Joy Garcia'
      image: joy.jpg
    - name: 'Cecille Alba'
      image: cecille.jpg
    - name: 'Quincy Gelacio'
      image: quincy.jpg
    - name: 'Julius Franco'
      image: julius.jpg
speakers:
  - full_name: 'Koichi Sasada'
    twitter: _ko1
    github: ko1
    image_filename: koichi_sasada.jpg
    description: >
      Koichi Sasada is a programmer, mainly developing Ruby interpreter (CRuby/MRI).
      He received Ph.D (Information Science and Technology) from the University of Tokyo, 2007.
      As first job, he was a faculty of University of Tokyo (Assistant associate 2006-2008, Assistant professor 2008-2012). 
      After the 13 years life in university, now, he is a member of Matz's team in Heroku, Inc. 
      He is also a director of Ruby Association.
  - full_name: 'Philip Arndt'
    twitter: parndt
    github: parndt
    image_filename: philip_arndt.jpeg
    description: >
      Kiwi programmer and Director of Ruby at Manuka Coalition, Philip is deeply interested in open source,
      travelling with his wife, sunshine and great food, making the Philippines a perfect fit -
      and not just because it starts with 'Philip'.

      Current President of Ruby New Zealand.
  - full_name: 'Richard Schneeman'
    twitter: schneems
    github: schneems
    image_filename: richard_schneeman.png
    description: >
      Richard writes Ruby at Heroku and maintains
      <a href: "http\:/\/codetriage.com", target: "_blank"> codetriage.com </a>
      When he isn't obsessively compulsively playing Starcraft 2, he writes such gems as Wicked,
      Sextant, and oPRO. Richard is a member of the Rails issue team, and is married to Ruby, literally.


# Build settings
markdown: kramdown
