# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubyconf.ph" # the base hostname & protocol for your site
meet_the_team:
  rubyists:
    - name: 'Christopher Rigor'
      twitter: crigor
      github: crigor
      image: christopher.jpg
    - name: 'Ramon Tayag'
      twitter: rtayag
      github: ramontayag
      image: ramon.jpeg
    - name: 'Eumir Gaspar'
      twitter: benjobatumbakal
      github: corroded
      image: eums.jpg
    - name: 'Chris Menina'
      github: kristm
      image: krist.png
  staff:
    - name: 'Sam Rigor'
      image: sam.jpg
    - name: 'Joy Garcia'
      image: joy.jpg
    - name: 'Cecille Alba'
      image: cecille.jpg
    - name: 'Quincy Gelacio'
      image: quincy.jpg
    - name: 'Julius Franco'
      image: julius.jpg
speakers:
  - full_name: Allan Espinosa
    twitter: AllanEspinosa
    github: aespinosa
    image_filename: allan_espinosa.jpeg
    description: >
      Allan runs large scale web infrastructure at Rakuten's internal Platform as a Service Cloud platform. He contributes in various DevOps tooling around Chef particularly open source Chef cookbooks. He advocates introducing quality to infrastructure code by providing extensive unit and functional tests.
  - full_name: Assaf Gelber
    twitter: assafgelber
    github: agelber
    image_filename: assaf_gelber.png
    description: >
      Assaf is a developer at the eBay Israel Innovation Center, a small team focused on creating the best products possible all the while working on various gems and side projects. As an amateur poker player, Assaf often likes to mix between the above.
  - full_name: Danish Khan
    twitter: danishkhan
    github: danishkhan
    image_filename: danish_khan.jpg
    description: >
      Danish finds teaching to be enjoyable and helps out at some of the local user groups. He currently resides in the beautiful city of San Francisco. He works at GitHub a company that helps developers work better together than alone. We also sell stickers & t-shirts.
  - full_name: Hiro Asari
    twitter: hiro_asari
    image_filename: hiro_asari.jpeg
    description: >
      Hiro Asari is a software developer at Travis CI GmbH and strong believer in open source. When he is not coding, he is found spending time with his family or appreciating fine beers of the world.
  - full_name: Joshua Lat
    twitter: mrjoshualat
    github: joshualat
    image_filename: joshua_lat.png
    description: >
      Joshua Lat serves as the Scrum Master, Full-Stack Developer, and Infrastructure Engineer of Deal Grocer, Taste Central, and BeautyMNL. In the past, he's known for winning the Kaspersky International Cup 2012 which made him interested in IT Security and E-commerce. When not playing NBA 2K15, he builds tools for himself to make his everyday life easier.
  - full_name: 'Koichi Sasada'
    twitter: _ko1
    github: ko1
    image_filename: koichi_sasada.jpg
    description: >
      Koichi Sasada is a programmer, mainly developing Ruby interpreter (CRuby/MRI).
      He received Ph.D (Information Science and Technology) from the University of Tokyo, 2007.
      As first job, he was a faculty of University of Tokyo (Assistant associate 2006-2008, Assistant professor 2008-2012).
      After the 13 years life in university, now, he is a member of Matz's team in Heroku, Inc.
      He is also a director of Ruby Association.
  - full_name: Maricris Nonato
    twitter:  maricris_sn
    github: maricris-sn
    image_filename: maricris_nonato.jpg
    description: >
      Maricris is a Senior Ruby on Rails developer at Premiere Speakers Bureau. A full-time remote worker, an asthmatic athlete who dreams of one day conquering a triathlon; she loves to take on tasks that are unfamiliar and new. She believes that learning is the only path to growth, having witnessed Rails from 1.x days and lived to tell its tale!
  - full_name: PJ Hagerty
    twitter: aspleenic
    github: aspleenic
    image_filename: pj_hagerty.png
    description: >
      A Ruby developer for the last several years, PJ currently works at Engine Yard as a Community Engineer. Additionally, he organizes the Western New York Ruby Brigade. Traveling to conferences and Ruby meet ups around the US and Canada, PJ likes to spread the word on the importance of community and coding, stressing the importance of outreach and focusing on the human side of being a coder.
  - full_name: 'Philip Arndt'
    twitter: parndt
    github: parndt
    image_filename: philip_arndt.jpeg
    description: >
      Kiwi programmer and Director of Ruby at Manuka Coalition, Philip is deeply interested in open source,
      travelling with his wife, sunshine and great food, making the Philippines a perfect fit -
      and not just because it starts with 'Philip'.

      Current President of Ruby New Zealand.
  - full_name: Radamanthus Batnag
    twitter: radamanthus
    github: radamanthus
    image_filename: radamanthus_batnag.jpg
    description: >
      Rad deals with crazy Passengers, wild Unicorns, and zombie Sidekiqs in his day job as a member of Engine Yard’s Support team.
  - full_name: 'Richard Schneeman'
    twitter: schneems
    github: schneems
    image_filename: richard_schneeman.png
    description: >
      Richard writes Ruby at Heroku and maintains
      <a href: "http\:/\/codetriage.com", target: "_blank"> codetriage.com </a>
      When he isn't obsessively compulsively playing Starcraft 2, he writes such gems as Wicked,
      Sextant, and oPRO. Richard is a member of the Rails issue team, and is married to Ruby, literally.
  - full_name: Steven Talcott Smith
    image_filename: steve_smith.jpeg
    description: >
      Steven is the founder of AELOGICA.  He is the author of Level UP - How to Become a Great Professional Software Developer. Steven fell in love with Ruby in 2006 and has enjoyed a 25 year career in IT.  He is the developer of Express Templates and lives with his family in Manila, Philippines and Lake Tahoe in the US.
  - full_name: Terence Lee
    twitter: hone02
    github: hone
    image_filename: terence_lee.jpg
    description: >
      Terence leads Heroku's Ruby Task Force curating the Ruby experience on the platform. He also works some OSS projects such as Ruby (the language), Bundler, as well as helping with the Rails Girls movement. When he's not going to an awesome Heroku or Ruby event, he lives in Austin, TX, the taco capital of America.
      Terence loves Friday hugs, EVERY DAY OF THE WEEK! Give him a big one when you see him! In addition to hugs, he believes in getting people together for #rubykaraoke.
  - full_name: Vipul Amler
    twitter: vipulnsward
    github: vipulnsward
    image_filename: vipul_amler.jpeg
    description: >
      Vipul works as a Software Consultant at BigBinary LLC. He is an avid Rails and Ruby Projects Contributor. His spare time is spent exploring and contributing to many Open Source ruby projects, when not dabbling with Clojure or React JS.
      Vipul loves Ruby's vibrant community and helps in building PuneRb, is the founder of and runs RubyIndia Community Newsletter and RubyIndia Podcast, and is an organiser for Deccan Ruby Conference.
  - full_name: Yuki Nishijima
    twitter: yuki24
    github: yuki24
    image_filename: yuki_nishijima.jpeg
    description: >
      Yuki is a Japanese Rubyist who was raised in Tokyo and used to live in Manila where he spent a year learning English. He is a maintainer of kaminari, the creator of did_you_mean, and a frequent contributor to many open source projects including Rails. He lives in New York, NY and works at Pivotal Labs NYC office to transform how the world builds software.
  - full_name: Yuki Sasada
    twitter: yotii23
    image_filename: yuki_sasada.jpg
    description: >
      Rails Web developer and the organizer of RailsGirls Tokyo. One of the authors of "Heroku for professionals (Japanese book  http://www.amazon.co.jp/dp/4048915134)" and a reviewer of the translation of "Ruby under a Microscope" Japanese version.
      She is working in Manyo (Everyleaf) corporation.
sponsors:
  gold:
    - image: aelogica.png
      description: >
        <p>ÆLOGICA is the premier Ruby on Rails and mobile development company with operations in the Philippines.</p>
        <p>ÆLOGICA provides team augmentation and rapid application development services to customers in the United States and around the world. ÆLOGICIANS are a dedicated team of professional developers, designers, enthusiasts, and problem-solvers with a passionate drive to make customers happy through technology.</p>
        <p>If you are looking for a great place to apply your skills and hone your craft, visit their careers page and apply.</p>
      website: http://aelogica.com
  silver:
    - image: launchpad_recruits.jpg
      description: >
        <p>We're are a team of Rails, media and mobile experts who are passionate about building a great product and learning new technologies.</p>
        <p>We've created an online video interviewing platform that helps employers make better and faster shortlisting decisions in their candidate screening process.</p>
        <p>We're looking for exceptional and like-minded Rails developers to join our team - <a href="http://launchpadrecruits.com/dev">learn more</a>.</p>
      website: http://launchpadrecruits.com/dev
  bronze:
    - image: gaiax_logo.gif
      website: http://en.gaiax.com/
  tickets:
    image: ticketbase.svg
    website: http://ticketbase.com

# Build settings
markdown: kramdown
