# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubyconf.ph" # the base hostname & protocol for your site
meet_the_team:
  rubyists:
    - name: 'Christopher Rigor'
      twitter: crigor
      github: crigor
      image: christopher.jpg
    - name: 'Eumir Gaspar'
      twitter: benjobatumbakal
      github: corroded
      image: eums.jpg
    - name: 'Chris Menina'
      github: kristm
      image: krist.png
    - name: 'Ramon Tayag'
      twitter: rtayag
      github: ramontayag
      image: ramon.jpg
  staff:
    - name: 'Sam Rigor'
      image: sam.jpg
    - name: 'Joy Garcia'
      image: joy.jpg
    - name: 'Cecille Alba'
      image: cecille.jpg
    - name: 'Quincy Gelacio'
      image: quincy.jpg
    - name: 'Julius Franco'
      image: julius.jpg
speakers:
  - full_name: Aaron Patterson
    twitter: tenderlove
    github: tenderlove
    image_filename: aaron_patterson.jpeg
    description: >
      By day, Aaron Patterson (tenderlove) is a mild mannered programmer for Red Hat whose Ruby code is almost as good looking as him. By night, he dons his Pink Warrior suit which gives him the power to contribute to many Open Source projects such as nokogiri, Ruby, and Rails. If you have seen someone kissing Matz or DHH at a conference, it was probably him.
  - full_name: Charles Nutter
    twitter: headius
    github: headius
    image_filename: charles_nutter.jpg
    description: >
      Charles Oliver Nutter works at Red Hat on JVM languages and hopes to help make OpenJDK the preferred platform for language development.
  - full_name: Akira Matsuda
    twitter: a_matsuda
    github: amatsuda
    image_filename: akira_matsuda.jpg
    description: > 
      Ruby committer, Rails committer, creator of widely used Rails plugins such as Kaminari, active_decorator, action_args, i18n_generators, html5_validators, motorhead, erd, database_rewinder, etc. 
      Chief Organizer of RubyKaigi 2015 and 2016. Founder of "Asakusa.rb", the most active Ruby community in Japan.
  - full_name: Assaf Gelber
    twitter: assafgelber 
    github: agelber
    image_filename: assaf_gelber.png
    description: >
      Assaf is a developer and Tech Ambassador at the PayPal Tel Aviv Consumer Product Center. Based out of sunny Tel Aviv, Assaf is also an amateur poker player, coffee brewer, and cake eater who loves using his tech knowledge for all his different hobbies.
  - full_name: Christophe Philemotte
    twitter: _toch
    github: toch
    image_filename: christophe_philemotte.jpg
    description: >
      Christophe is the founder of PullReview, an automated code review for Ruby and Rails. He is a Ruby and C++ developer. When he's not writing disease simulators or PullReview, he helps others with development challenges, writes blog post, has co-founded Ruby Belgium, and likes to talk at conferences.
  - full_name: Claudio Baccigalupo
    twitter: 
    github: claudiob
    image_filename:
    description: >
      Claudio is a member of the Rails Issues team, a frequent contributor to the Rails source code (over 150 commits), the organizer of the L.A. Ruby/Rails meetup and one of the authors of the weekly newsletter "This week in Rails".
  - full_name: Ejay Canaria
    twitter: iamejay
    github: ejaypcanaria
    image_filename: ejay_canaria.jpeg
    description: >
      Ejay Canaria is a curiosity follower and software writer. He's from the Philippines and is currently working as a software engineer in Singapore for TradeGecko. He's into Ruby and Javascript. When not coding, he is probably playing with his guitars or reading an eBook.
  - full_name: Isha Tripathi
    twitter: TripathiIsha
    github: isha-tripathi
    image_filename: isha_tripathi.jpg
    description: >
      Isha is a multi-tasker at ThoughtWorks India. She likes to dabble in a lot of new tools and technologies. In her spare time she likes to read, salsa and travel. She has played different roles on her teams, including but not limited to being a developer and business analyst. She is a passionate feminist, and a proud supporter of equality in the workspace.
schedule:
  - title: March 26
    events:
      - time: '01:00pm'
        title: Scuba Diving (You can still join us! Send us an email.)
        break: true
      - time: '07:30pm-11:00pm'
        title: Pool Party
        speaker: Crown Regency Beach Resort (Station 3 beachfront, this is NOT the conference hotel)
  - title: March 27
    events:
      - time: '08:30am-09:25am'
        title: Registration
        break: true
      - time: '09:25am-09:30am'
        title: Welcome Remarks
        speaker: Christopher Rigor
      - time: '09:30am-10:15am'
        title: 'Ruby 2.2: GC Improvement Report'
        speaker: Koichi Sasada
        description: >
          Nullam vitae lacinia tellus, quis vehicula sem. Nam sagittis felis ut sagittis pharetra. Suspendisse nec diam mauris. Proin vel risus at lectus sodales mattis. Morbi et sapien nec eros facilisis varius id eget ante. Sed efficitur sem id urna fringilla, eget faucibus nisl semper. Suspendisse auctor enim dapibus molestie mattis. Sed ac ante justo. Aenean rutrum ligula sed dictum dictum. Nam sed ante eget tellus sodales viverra.
      - time: '10:15am-10:45am'
        title: Optimizing Your Poker Game With the Help of Ruby
        speaker: Assaf Gelber
        description: >
          Nullam vitae lacinia tellus, quis vehicula sem. Nam sagittis felis ut sagittis pharetra. Suspendisse nec diam mauris. Proin vel risus at lectus sodales mattis. Morbi et sapien nec eros facilisis varius id eget ante. Sed efficitur sem id urna fringilla, eget faucibus nisl semper. Suspendisse auctor enim dapibus molestie mattis. Sed ac ante justo. Aenean rutrum ligula sed dictum dictum. Nam sed ante eget tellus sodales viverra.
      - time: '10:45am-11:00am'
        break: true
        title: BREAK
      - time: '11:00am-11:30am'
        title: Sketching for Programmers
        speaker: Radamanthus Batnag
      - time: '11:30am-12:00pm'
        title: Getting that Rails Project to Launch on Time
        speaker: Joshua Lat
      - time: '12:00pm-1:00pm'
        break: true
        title: LUNCH
      - time: '01:00pm-01:30pm'
        title: A Few Things I Know About Ruby Implementation
        speaker: Yuki Sasada
      - time: '01:30pm-02:00pm'
        title: Everyone's in Sales
        speaker: Danish Khan
      - time: '02:00pm-02:15pm'
        break: true
        title: BREAK
      - time: '02:15pm-02:45pm'
        title: Coding Confidently in Ruby
        speaker: Maricris Nonato
      - time: '02:45pm-03:15pm'
        title: A Brief History of Time (for Rubyists)
        speaker: Hiro Asari
      - time: '03:45pm'
        title: Water Activities
        speaker: Station 3
      - time: '04:30pm'
        title: Snacks and drinks
        speaker: Crown Regency Beach Resort (Station 3 beachfront)

  - title: March 28
    events:
      - time: '10:00am-10:45am'
        title: Ruby Science
        speaker: Richard Schneeman
      - time: '10:45am-11:15am'
        title: 'Ruby Objects: A Walkabout'
        speaker: Terence Lee
      - time: '11:15am-11:30am'
        break: true
        title: BREAK
      - time: '11:30am-12:00pm'
        title: 'Treat your servers like your Ruby App: Infrastructure as Code'
        speaker: Allan Espinosa
      - time: '12:00pm-12:30pm'
        title: Increasing Your Value as a Developer
        speaker: Steven Talcott Smith
      - time: '12:30pm-1:30pm'
        break: true
        title: LUNCH
      - time: '01:30pm-02:00pm'
        title: 'Urban Legends: What You Code Makes You Who You Are'
        speaker: PJ Hagerty
      - time: '02:00pm-02:30pm'
        title: Rails <3 React
        speaker: Vipul Amler
      - time: '02:30pm-02:45pm'
        break: true
        title: BREAK
      - time: '02:45pm-03:15pm'
        title: How `did_you_mean` gem works
        speaker: Yuki Nishijima
      - time: '03:15pm-03:45pm'
        title: Succeeding with Open Source
        speaker: Phil Arndt
      - time: '03:45pm-04:15pm'
        break: true
        title: BREAK
      - time: '04:15pm-05:15pm'
        break: true
        title: Lightning Talks
      - time: '06:00pm-10:00pm'
        title: 'After-party and #RubyKaraoke'
        speaker: Ocean Bar

sponsors:
  gold:
    - image: aelogica.png
      description: >
        <p>ÆLOGICA is the premier Ruby on Rails and mobile development company with operations in the Philippines.</p>
        <p>ÆLOGICA provides team augmentation and rapid application development services to customers in the United States and around the world. ÆLOGICIANS are a dedicated team of professional developers, designers, enthusiasts, and problem-solvers with a passionate drive to make customers happy through technology.</p>
        <p>If you are looking for a great place to apply your skills and hone your craft, visit their careers page and apply.</p>
      website: http://aelogica.com
  silver:
    - image: launchpad_recruits.jpg
      description: >
        <p>We're are a team of Rails, media and mobile experts who are passionate about building a great product and learning new technologies.</p>
        <p>We've created an online video interviewing platform that helps employers make better and faster shortlisting decisions in their candidate screening process.</p>
        <p>We're looking for exceptional and like-minded Rails developers to join our team - <a href="http://launchpadrecruits.com/dev">learn more</a>.</p>
      website: http://launchpadrecruits.com/dev
  bronze:
    - image: gaiax_logo.gif
      website: http://en.gaiax.com/
    - image: engine_yard.png
      website: https://www.engineyard.com/
  tickets:
    image: ticketbase.svg
    website: http://ticketbase.com

# Build settings
markdown: kramdown
